# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "DRUGS" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"userInput" VARCHAR NOT NULL,"userToken" VARCHAR NOT NULL,"source" VARCHAR,"resolved_drug_type_id" BIGINT);
create table "DRUG_GROUPS" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL);
create table "DRUG_GROUPS_TYPES" ("drug_group_id" BIGINT NOT NULL,"drug_type_id" BIGINT NOT NULL);
alter table "DRUG_GROUPS_TYPES" add constraint "DRUG_GROUPS_TYPES_PK" primary key("drug_group_id","drug_type_id");
create table "DRUG_TYPES" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"generic_type_id" BIGINT);
create table "EXPRESSION_TERMS" ("label" VARCHAR NOT NULL PRIMARY KEY,"drug_type_id" BIGINT,"drug_group_id" BIGINT,"statement" VARCHAR);
create table "EXPRESSION_TERMS_RULES" ("expression_term_label" VARCHAR NOT NULL,"rule_id" BIGINT NOT NULL);
alter table "EXPRESSION_TERMS_RULES" add constraint "EXPRESSION_TERMS_RULES_PK" primary key("expression_term_label","rule_id");
create table "RULE" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"condition_expression" VARCHAR NOT NULL,"source" VARCHAR,"note" VARCHAR);
create table "STATEMENT_TERMS_USER_SESSIONS" ("user_session_token" VARCHAR NOT NULL,"statement_term_label" VARCHAR NOT NULL);
alter table "STATEMENT_TERMS_USER_SESSIONS" add constraint "STATEMENT_TERMS_USER_SESSIONS_PK" primary key("user_session_token","statement_term_label");
create table "SUGGESTIONS" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"text" VARCHAR NOT NULL,"explanatory_note" VARCHAR,"rule_id" BIGINT NOT NULL);
create table "USER_SESSIONS" ("token" VARCHAR NOT NULL PRIMARY KEY);
alter table "DRUGS" add constraint "DRUGS_RESOLVED_TYPE_FK" foreign key("resolved_drug_type_id") references "DRUG_TYPES"("id") on update NO ACTION on delete NO ACTION;
alter table "DRUG_GROUPS_TYPES" add constraint "DRUG_GROUPS_TYPES_GROUP_FK" foreign key("drug_group_id") references "DRUG_GROUPS"("id") on update NO ACTION on delete NO ACTION;
alter table "DRUG_GROUPS_TYPES" add constraint "DRUG_GROUPS_TYPES_TYPE_FK" foreign key("drug_type_id") references "DRUG_TYPES"("id") on update NO ACTION on delete NO ACTION;
alter table "DRUG_TYPES" add constraint "DRUG_TYPE_GENERIC_TYPE_FK" foreign key("generic_type_id") references "DRUG_TYPES"("id") on update NO ACTION on delete NO ACTION;
alter table "EXPRESSION_TERMS" add constraint "EXPRESSION_TERMS_DRUG_GROUP_FK" foreign key("drug_group_id") references "DRUG_GROUPS"("id") on update NO ACTION on delete NO ACTION;
alter table "EXPRESSION_TERMS" add constraint "EXPRESSION_TERMS_DRUG_TYPE_FK" foreign key("drug_type_id") references "DRUG_TYPES"("id") on update NO ACTION on delete NO ACTION;
alter table "EXPRESSION_TERMS_RULES" add constraint "EXPRESSION_TERMS_RULES_EXPRESSION_TERM_FK" foreign key("expression_term_label") references "EXPRESSION_TERMS"("label") on update NO ACTION on delete NO ACTION;
alter table "EXPRESSION_TERMS_RULES" add constraint "EXPRESSION_TERMS_RULES_RULE_FK" foreign key("rule_id") references "RULE"("id") on update NO ACTION on delete NO ACTION;
alter table "STATEMENT_TERMS_USER_SESSIONS" add constraint "STATEMENT_TERMS_USER_SESSIONS_USER_SESSION_FK" foreign key("user_session_token") references "USER_SESSIONS"("token") on update NO ACTION on delete NO ACTION;
alter table "STATEMENT_TERMS_USER_SESSIONS" add constraint "STATEMENT_TERMS_USER_SESSIONS_STATEMENT_TERM_FK" foreign key("statement_term_label") references "EXPRESSION_TERMS"("label") on update NO ACTION on delete NO ACTION;
alter table "SUGGESTIONS" add constraint "SUGGESTIONS_RULE_FK" foreign key("rule_id") references "RULE"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "DRUGS" drop constraint "DRUGS_RESOLVED_TYPE_FK";
alter table "DRUG_GROUPS_TYPES" drop constraint "DRUG_GROUPS_TYPES_GROUP_FK";
alter table "DRUG_GROUPS_TYPES" drop constraint "DRUG_GROUPS_TYPES_TYPE_FK";
alter table "DRUG_TYPES" drop constraint "DRUG_TYPE_GENERIC_TYPE_FK";
alter table "EXPRESSION_TERMS" drop constraint "EXPRESSION_TERMS_DRUG_GROUP_FK";
alter table "EXPRESSION_TERMS" drop constraint "EXPRESSION_TERMS_DRUG_TYPE_FK";
alter table "EXPRESSION_TERMS_RULES" drop constraint "EXPRESSION_TERMS_RULES_EXPRESSION_TERM_FK";
alter table "EXPRESSION_TERMS_RULES" drop constraint "EXPRESSION_TERMS_RULES_RULE_FK";
alter table "STATEMENT_TERMS_USER_SESSIONS" drop constraint "STATEMENT_TERMS_USER_SESSIONS_USER_SESSION_FK";
alter table "STATEMENT_TERMS_USER_SESSIONS" drop constraint "STATEMENT_TERMS_USER_SESSIONS_STATEMENT_TERM_FK";
alter table "SUGGESTIONS" drop constraint "SUGGESTIONS_RULE_FK";
drop table "DRUGS";
drop table "DRUG_GROUPS";
alter table "DRUG_GROUPS_TYPES" drop constraint "DRUG_GROUPS_TYPES_PK";
drop table "DRUG_GROUPS_TYPES";
drop table "DRUG_TYPES";
drop table "EXPRESSION_TERMS";
alter table "EXPRESSION_TERMS_RULES" drop constraint "EXPRESSION_TERMS_RULES_PK";
drop table "EXPRESSION_TERMS_RULES";
drop table "RULE";
alter table "STATEMENT_TERMS_USER_SESSIONS" drop constraint "STATEMENT_TERMS_USER_SESSIONS_PK";
drop table "STATEMENT_TERMS_USER_SESSIONS";
drop table "SUGGESTIONS";
drop table "USER_SESSIONS";

